# Generated by Django 3.0.8 on 2021-03-28 23:54

import API.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_discorduser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', API.managers.DiscordUserOauth2Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
