# Generated by Django 3.0.8 on 2021-03-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210328_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
