# Generated by Django 3.0.8 on 2021-03-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_discorduser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='is_active',
        ),
    ]
