name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing node dependencies
      run: npm install
      working-directory: ./frontend
    
    - name: Performing React build 
      run: npm run build --if-present
      working-directory: ./frontend
      env:
        CI: false # causes warnings to become errors, and there are tons of pa11y errors to fix

    - name: Performing React tests if any defined 
      run: npm test
      working-directory: ./frontend
      env:
        CI: true # so that the test prompt doesn't show up
